export const AIRPORTS = [
  {
    name: 'Pakyong Airport',
    city: 'Pakyong',
    code: 'PYG',
    country: 'India',
  },
  {
    name: 'Ayodhya Airport',
    city: 'Faizabad',
    code: 'AYJ',
    country: 'India',
  },
  {
    name: 'Jindal Vijaynagar Airport',
    city: 'Toranagallu',
    code: 'VDY',
    country: 'India',
  },
  {
    name: 'Deoghar Airport',
    city: 'Deoghar',
    code: 'DGH',
    country: 'India',
  },
  {
    name: 'Navi Mumbai International Airport (under construction)',
    city: 'Navi Mumbai',
    code: 'NMI',
    country: 'India',
  },
  {
    name: 'Mopa International Airport',
    city: 'Mopa',
    code: 'GOX',
    country: 'India',
  },
  {
    name: 'Rashtrakavi Kuvempu Airport',
    city: 'Shimoga',
    code: 'RQY',
    country: 'India',
  },
  {
    name: 'Itanagar Donyi Polo Hollongi Airport',
    city: 'Hollongi',
    code: 'HGI',
    country: 'India',
  },
  {
    name: 'Utkela Airport',
    city: 'Bhawanipatna',
    code: 'UKE',
    country: 'India',
  },
  {
    name: 'Jagdalpur Airport',
    city: 'Jagdalpur',
    code: 'JGB',
    country: 'India',
  },
  {
    name: 'Neyveli Airport',
    city: 'Neyveli',
    code: 'NVY',
    country: 'India',
  },
  {
    name: 'Rajouri Airport',
    city: 'Rajouri',
    code: 'RJI',
    country: 'India',
  },
  {
    name: 'Tezu Airport',
    city: 'Tezu',
    code: 'TEI',
    country: 'India',
  },
  {
    name: 'Osmanabad Airport',
    city: 'Osmanabad',
    code: 'OMN',
    country: 'India',
  },
  {
    name: 'Rewa Airport, Chorhata, REWA',
    city: 'Rewa',
    code: 'REW',
    country: 'India',
  },
  {
    name: 'Diu Airport',
    city: 'Diu',
    code: 'DIU',
    country: 'India',
  },
  {
    name: 'Gondia Airport',
    city: 'Gondia',
    code: 'GDB',
    country: 'India',
  },
  {
    name: 'Sardar Vallabh Bhai Patel International Airport',
    city: 'Ahmedabad',
    code: 'AMD',
    country: 'India',
  },
  {
    name: 'Akola Airport',
    city: 'Akola',
    code: 'AKD',
    country: 'India',
  },
  {
    name: 'Aurangabad Airport',
    city: 'Aurangabad',
    code: 'IXU',
    country: 'India',
  },
  {
    name: 'Chhatrapati Shivaji International Airport',
    city: 'Mumbai',
    code: 'BOM',
    country: 'India',
  },
  {
    name: 'Bilaspur Airport',
    city: 'Bilaspur',
    code: 'PAB',
    country: 'India',
  },
  {
    name: 'Bhuj Airport',
    city: 'Bhuj',
    code: 'BHJ',
    country: 'India',
  },
  {
    name: 'Belagavi Airport',
    city: 'Belgaum',
    code: 'IXG',
    country: 'India',
  },
  {
    name: 'Vadodara Airport',
    city: 'Vadodara',
    code: 'BDQ',
    country: 'India',
  },
  {
    name: 'Raja Bhoj International Airport',
    city: 'Bhopal',
    code: 'BHO',
    country: 'India',
  },
  {
    name: 'Bhavnagar Airport',
    city: 'Bhavnagar',
    code: 'BHU',
    country: 'India',
  },
  {
    name: 'Daman Airport',
    city: 'Daman',
    code: 'NMB',
    country: 'India',
  },
  {
    name: 'Guna Airport',
    code: 'GUX',
    country: 'India',
  },
  {
    name: 'Dabolim Airport',
    city: 'Vasco da Gama',
    code: 'GOI',
    country: 'India',
  },
  {
    name: 'Hubli Airport',
    city: 'Hubli',
    code: 'HBX',
    country: 'India',
  },
  {
    name: 'Rajkot International Airport',
    city: 'Rajkot',
    code: 'HSR',
    country: 'India',
  },
  {
    name: 'Devi Ahilyabai Holkar Airport',
    city: 'Indore',
    code: 'IDR',
    country: 'India',
  },
  {
    name: 'Jabalpur Airport',
    city: 'Jabalpur',
    code: 'JLR',
    country: 'India',
  },
  {
    name: 'Jamnagar Airport',
    city: 'Jamnagar',
    code: 'JGA',
    country: 'India',
  },
  {
    name: 'Kandla Airport',
    city: 'Kandla',
    code: 'IXY',
    country: 'India',
  },
  {
    name: 'Khajuraho Airport',
    city: 'Khajuraho',
    code: 'HJR',
    country: 'India',
  },
  {
    name: 'Kolhapur Airport',
    city: 'Kolhapur',
    code: 'KLH',
    country: 'India',
  },
  {
    name: 'Keshod Airport',
    city: 'Keshod',
    code: 'IXK',
    country: 'India',
  },
  {
    name: 'Nanded Airport',
    city: 'Nanded',
    code: 'NDC',
    country: 'India',
  },
  {
    name: 'Dr. Babasaheb Ambedkar International Airport',
    city: 'Nagpur',
    code: 'NAG',
    country: 'India',
  },
  {
    name: 'Nashik Airport',
    city: 'Nasik',
    code: 'ISK',
    country: 'India',
  },
  {
    name: 'Pune Airport / Lohagaon Air Force Station',
    city: 'Pune',
    code: 'PNQ',
    country: 'India',
  },
  {
    name: 'Porbandar Airport',
    city: 'Porbandar',
    code: 'PBD',
    country: 'India',
  },
  {
    name: 'Ratnagiri Airport',
    code: 'RTC',
    country: 'India',
  },
  {
    name: 'Rajkot Airport',
    city: 'Rajkot',
    code: 'RAJ',
    country: 'India',
  },
  {
    name: 'Swami Vivekananda Airport',
    city: 'Raipur',
    code: 'RPR',
    country: 'India',
  },
  {
    name: 'Shirdi Airport',
    city: 'Kakadi',
    code: 'SAG',
    country: 'India',
  },
  {
    name: 'Solapur Airport',
    city: 'Solapur',
    code: 'SSE',
    country: 'India',
  },
  {
    name: 'Surat Airport',
    city: 'Surat',
    code: 'STV',
    country: 'India',
  },
  {
    name: 'Maharana Pratap Airport',
    city: 'Udaipur',
    code: 'UDR',
    country: 'India',
  },
  {
    name: 'Darbhanga Airport',
    city: 'Darbhanga',
    code: 'DBR',
    country: 'India',
  },
  {
    name: 'Azamgarh Airport',
    city: 'Azamgarh',
    code: 'AZH',
    country: 'India',
  },
  {
    name: 'Along Airport',
    code: 'IXV',
    country: 'India',
  },
  {
    name: 'Agartala - Maharaja Bir Bikram Airport',
    city: 'Agartala',
    code: 'IXA',
    country: 'India',
  },
  {
    name: 'Bagdogra Airport',
    city: 'Siliguri',
    code: 'IXB',
    country: 'India',
  },
  {
    name: 'Balurghat Airport',
    city: 'Balurghat',
    code: 'RGH',
    country: 'India',
  },
  {
    name: 'Shillong Airport',
    city: 'Shillong',
    code: 'SHL',
    country: 'India',
  },
  {
    name: 'Biju Patnaik Airport',
    city: 'Bhubaneswar',
    code: 'BBI',
    country: 'India',
  },
  {
    name: 'Netaji Subhash Chandra Bose International Airport',
    city: 'Kolkata',
    code: 'CCU',
    country: 'India',
  },
  {
    name: 'Cooch Behar Airport',
    city: 'Cooch Behar',
    code: 'COH',
    country: 'India',
  },
  {
    name: 'Chitrakoot Airport',
    city: 'Chitrakoot',
    code: 'CWK',
    country: 'India',
  },
  {
    name: 'Dhanbad Airport',
    code: 'DBD',
    country: 'India',
  },
  {
    name: 'Kazi Nazrul Islam Airport',
    city: 'Durgapur',
    code: 'RDP',
    country: 'India',
  },
  {
    name: 'Daporijo Airport',
    city: 'Daporijo',
    code: 'DEP',
    country: 'India',
  },
  {
    name: 'Gorakhpur Airport',
    city: 'Gorakhpur',
    code: 'GOP',
    country: 'India',
  },
  {
    name: 'Lokpriya Gopinath Bordoloi International Airport',
    city: 'Guwahati',
    code: 'GAU',
    country: 'India',
  },
  {
    name: 'Gaya Airport',
    city: 'Gaya',
    code: 'GAY',
    country: 'India',
  },
  {
    name: 'Imphal Airport',
    city: 'Imphal',
    code: 'IMF',
    country: 'India',
  },
  {
    name: 'Jharsuguda Airport',
    code: 'JRG',
    country: 'India',
  },
  {
    name: 'Jeypore Airport',
    city: 'Jeypore',
    code: 'PYB',
    country: 'India',
  },
  {
    name: 'Sonari Airport',
    city: 'Jamshedpur',
    code: 'IXW',
    country: 'India',
  },
  {
    name: 'Jorhat Airport',
    city: 'Jorhat',
    code: 'JRH',
    country: 'India',
  },
  {
    name: 'Kushinagar International Airport',
    city: 'Kushinagar',
    code: 'KBK',
    country: 'India',
  },
  {
    name: 'Kamalpur Airport',
    city: 'Manik Bhandar',
    code: 'IXQ',
    country: 'India',
  },
  {
    name: 'Kailashahar Airport',
    city: 'Kailashahar',
    code: 'IXH',
    country: 'India',
  },
  {
    name: 'Silchar Airport',
    city: 'Silchar',
    code: 'IXS',
    country: 'India',
  },
  {
    name: 'Khowai Airport',
    city: 'Khowai',
    code: 'IXN',
    country: 'India',
  },
  {
    name: 'Lengpui Airport',
    city: 'Aizawl (Lengpui)',
    code: 'AJL',
    country: 'India',
  },
  {
    name: 'Lilabari North Lakhimpur Airport',
    city: 'Lilabari',
    code: 'IXI',
    country: 'India',
  },
  {
    name: 'Malda Airport',
    city: 'Malda',
    code: 'LDA',
    country: 'India',
  },
  {
    name: 'Dibrugarh Airport',
    city: 'Dibrugarh',
    code: 'DIB',
    country: 'India',
  },
  {
    name: 'Dimapur Airport',
    city: 'Dimapur',
    code: 'DMU',
    country: 'India',
  },
  {
    name: 'Muzaffarpur Airport',
    city: 'Muzaffarpur',
    code: 'MZU',
    country: 'India',
  },
  {
    name: 'Pasighat Airport',
    city: 'Pasighat',
    code: 'IXT',
    country: 'India',
  },
  {
    name: 'Jay Prakash Narayan Airport',
    city: 'Patna',
    code: 'PAT',
    country: 'India',
  },
  {
    name: 'Birsa Munda Airport',
    city: 'Ranchi',
    code: 'IXR',
    country: 'India',
  },
  {
    name: 'Rourkela Airport',
    city: 'Rourkela',
    code: 'RRK',
    country: 'India',
  },
  {
    name: 'Rupsi Airport',
    city: 'Rupsi',
    code: 'RUP',
    country: 'India',
  },
  {
    name: 'Tezpur Airport',
    code: 'TEZ',
    country: 'India',
  },
  {
    name: 'Visakhapatnam Airport',
    city: 'Visakhapatnam',
    code: 'VTZ',
    country: 'India',
  },
  {
    name: 'Ziro Airport',
    city: 'Ziro',
    code: 'ZER',
    country: 'India',
  },
  {
    name: 'Agra Airport / Agra Air Force Station',
    city: 'Agra',
    code: 'AGR',
    country: 'India',
  },
  {
    name: 'Aligarh Airport',
    city: 'Aligarh',
    code: 'HRH',
    country: 'India',
  },
  {
    name: 'Prayagraj Airport',
    city: 'Allahabad',
    code: 'IXD',
    country: 'India',
  },
  {
    name: 'Sri Guru Ram Dass Jee International Airport',
    city: 'Amritsar',
    code: 'ATQ',
    country: 'India',
  },
  {
    name: 'Adampur Airport',
    city: 'Adampur',
    code: 'AIP',
    country: 'India',
  },
  {
    name: 'Nal Airport',
    city: 'Bikaner',
    code: 'BKB',
    country: 'India',
  },
  {
    name: 'Lal Bahadur Shastri Airport',
    city: 'Varanasi',
    code: 'VNS',
    country: 'India',
  },
  {
    name: 'Kullu Manali Airport',
    city: 'Bhuntar',
    code: 'KUU',
    country: 'India',
  },
  {
    name: 'Bhatinda Air Force Station',
    code: 'BUP',
    country: 'India',
  },
  {
    name: 'Bareilly Air Force Station',
    city: 'Bareilly',
    code: 'BEK',
    country: 'India',
  },
  {
    name: 'Chandigarh International Airport',
    city: 'Chandigarh',
    code: 'IXC',
    country: 'India',
  },
  {
    name: 'Kanpur Airport',
    city: 'Kanpur',
    code: 'KNU',
    country: 'India',
  },
  {
    name: 'Dehradun Jolly Grant Airport',
    city: 'Dehradun (Jauligrant)',
    code: 'DED',
    country: 'India',
  },
  {
    name: 'Indira Gandhi International Airport',
    city: 'New Delhi',
    code: 'DEL',
    country: 'India',
  },
  {
    name: 'Hindon Airport / Hindon Air Force Station',
    city: 'Ghaziabad',
    code: 'HDO',
    country: 'India',
  },
  {
    name: 'Kangra Airport',
    city: 'Kangra',
    code: 'DHM',
    country: 'India',
  },
  {
    name: 'Gwalior Airport',
    city: 'Gwalior',
    code: 'GWL',
    country: 'India',
  },
  {
    name: 'Hisar Airport',
    city: 'Hisar',
    code: 'HSS',
    country: 'India',
  },
  {
    name: 'Jodhpur Airport',
    city: 'Jodhpur',
    code: 'JDH',
    country: 'India',
  },
  {
    name: 'Jaipur International Airport',
    city: 'Jaipur',
    code: 'JAI',
    country: 'India',
  },
  {
    name: 'Jaisalmer Airport',
    code: 'JSA',
    country: 'India',
  },
  {
    name: 'Jammu Airport',
    city: 'Jammu',
    code: 'IXJ',
    country: 'India',
  },
  {
    name: 'Kishangarh Airport Ajmer',
    city: 'Ajmer (Kishangarh)',
    code: 'KQH',
    country: 'India',
  },
  {
    name: 'Kota Airport',
    city: 'Kota',
    code: 'KTU',
    country: 'India',
  },
  {
    name: 'Ludhiana Airport',
    code: 'LUH',
    country: 'India',
  },
  {
    name: 'Leh Kushok Bakula Rimpochee Airport',
    city: 'Leh',
    code: 'IXL',
    country: 'India',
  },
  {
    name: 'Chaudhary Charan Singh International Airport',
    city: 'Lucknow',
    code: 'LKO',
    country: 'India',
  },
  {
    name: 'Pathankot Airport',
    city: 'Pathankot',
    code: 'IXP',
    country: 'India',
  },
  {
    name: 'Pantnagar Airport',
    city: 'Pantnagar',
    code: 'PGH',
    country: 'India',
  },
  {
    name: 'Shimla Airport',
    city: 'Jubbarhatti',
    code: 'SLV',
    country: 'India',
  },
  {
    name: 'Sheikh ul Alam International Airport',
    city: 'Srinagar',
    code: 'SXR',
    country: 'India',
  },
  {
    name: 'Satna Airport',
    code: 'TNI',
    country: 'India',
  },
  {
    name: 'Shravasti Airport',
    city: 'Shravasti',
    code: 'VSV',
    country: 'India',
  },
  {
    name: 'Murod Kond Airport',
    city: 'Latur',
    code: 'LTU',
    country: 'India',
  },
  {
    name: 'Tuticorin Airport',
    city: 'Vagaikulam',
    code: 'TCR',
    country: 'India',
  },
  {
    name: 'Agatti Airport',
    city: 'Agatti',
    code: 'AGX',
    country: 'India',
  },
  {
    name: 'Bellary Airport',
    city: 'Bellary',
    code: 'BEP',
    country: 'India',
  },
  {
    name: 'Kempegowda International Airport',
    city: 'Bangalore',
    code: 'BLR',
    country: 'India',
  },
  {
    name: 'Bidar Airport / Bidar Air Force Station',
    city: 'Bidar',
    code: 'IXX',
    country: 'India',
  },
  {
    name: 'Vijayawada Airport',
    city: 'Gannavaram',
    code: 'VGA',
    country: 'India',
  },
  {
    name: 'Coimbatore International Airport',
    city: 'Coimbatore',
    code: 'CJB',
    country: 'India',
  },
  {
    name: 'Cochin International Airport',
    city: 'Kochi',
    code: 'COK',
    country: 'India',
  },
  {
    name: 'Calicut International Airport',
    city: 'Calicut',
    code: 'CCJ',
    country: 'India',
  },
  {
    name: 'Kadapa Airport',
    city: 'Kadapa',
    code: 'CDP',
    country: 'India',
  },
  {
    name: 'Car Nicobar Air Force Base',
    city: 'IAF Camp',
    code: 'CBD',
    country: 'India',
  },
  {
    name: 'Kalaburagi Airport',
    city: 'Kalaburagi',
    code: 'GBI',
    country: 'India',
  },
  {
    name: 'Rajiv Gandhi International Airport',
    city: 'Hyderabad',
    code: 'HYD',
    country: 'India',
  },
  {
    name: 'Begumpet Airport',
    city: 'Hyderabad',
    code: 'BPM',
    country: 'India',
  },
  {
    name: 'Kannur International Airport',
    city: 'Kannur',
    code: 'CNN',
    country: 'India',
  },
  {
    name: 'Kurnool Airport',
    city: 'Orvakal',
    code: 'KJB',
    country: 'India',
  },
  {
    name: 'Madurai Airport',
    city: 'Madurai',
    code: 'IXM',
    country: 'India',
  },
  {
    name: 'Mangalore International Airport',
    city: 'Mangalore',
    code: 'IXE',
    country: 'India',
  },
  {
    name: 'Chennai International Airport',
    city: 'Chennai',
    code: 'MAA',
    country: 'India',
  },
  {
    name: 'Mysore Airport',
    city: 'Mysore',
    code: 'MYQ',
    country: 'India',
  },
  {
    name: 'Veer Savarkar International Airport / INS Utkrosh',
    city: 'Port Blair',
    code: 'IXZ',
    country: 'India',
  },
  {
    name: 'Pondicherry Airport',
    city: 'Puducherry (Pondicherry)',
    code: 'PNY',
    country: 'India',
  },
  {
    name: 'Sri Sathya Sai Airport',
    city: 'Puttaparthi',
    code: 'PUT',
    country: 'India',
  },
  {
    name: 'Basanth Nagar Airport',
    city: 'Ramagundam',
    code: 'RMD',
    country: 'India',
  },
  {
    name: 'Rajahmundry Airport',
    city: 'Madhurapudi',
    code: 'RJA',
    country: 'India',
  },
  {
    name: 'Salem Airport',
    city: 'Salem',
    code: 'SXV',
    country: 'India',
  },
  {
    name: 'Sindhudurg Airport',
    city: 'Sindhudurg',
    code: 'SDW',
    country: 'India',
  },
  {
    name: 'Thanjavur Air Force Station',
    city: 'Thanjavur',
    code: 'TJV',
    country: 'India',
  },
  {
    name: 'Tirupati Airport',
    city: 'Tirupati',
    code: 'TIR',
    country: 'India',
  },
  {
    name: 'Tiruchirappalli International Airport',
    city: 'Tiruchirappalli',
    code: 'TRZ',
    country: 'India',
  },
  {
    name: 'Thiruvananthapuram International Airport',
    city: 'Thiruvananthapuram',
    code: 'TRV',
    country: 'India',
  },
  {
    name: 'Warangal Airport',
    city: 'Warangal',
    code: 'WGC',
    country: 'India',
  },
];
