import { Flight } from '../interfaces/flight-response.interface';

export const FLIGHTS: Flight[] = [
  {
    airlineName: $localize`Air India`,
    airlineId: `Air India`,
    airlineLogo: '',
    departureDate: new Date('01/12/2024 4:50'),
    arrivalDate: new Date('01/12/2024 9:10'),
    departureInMillies: 0,
    arrivalInMillies: 0,
    departureTimeDisplay: '',
    arrivalTimeDisplay: '',
    durationDisplay: '',
    durationInMillies: 0,
    departureAirportCode: '',
    arrivalAirportCode: '',
    stops: [
      {
        code: 'PUN',
        name: 'Pune Airport',
        country: 'India',
        city: 'Pune',
      },
    ],
    classTypes: [
      { code: 'BC', name: $localize`Basic`, price: 110, seatsLeft: null },
      { code: 'MN', name: $localize`Main`, price: 240, seatsLeft: null },
      { code: 'EC', name: $localize`Economy`, price: 475, seatsLeft: 3 },
    ],
  },
  {
    airlineName: $localize`Vistara Airways`,
    airlineId: `Vistara Airways`,
    airlineLogo: '',
    departureDate: new Date('01/12/2024 14:30'),
    arrivalDate: new Date('01/12/2024 19:50'),
    departureInMillies: 0,
    arrivalInMillies: 0,
    departureTimeDisplay: '',
    arrivalTimeDisplay: '',
    durationDisplay: '',
    durationInMillies: 0,
    departureAirportCode: '',
    arrivalAirportCode: '',
    stops: [],
    classTypes: [
      { code: 'BC', name: $localize`Basic`, price: 180, seatsLeft: null },
      { code: 'MN', name: $localize`Main`, price: 240, seatsLeft: null },
      { code: 'EC', name: $localize`Economy`, price: 475, seatsLeft: null },
    ],
  },
  {
    airlineName: $localize`Indigo Airline`,
    airlineId: `Indigo Airline`,
    airlineLogo: '',
    departureDate: new Date('01/12/2024 1:30'),
    arrivalDate: new Date('01/12/2024 4:30'),
    departureInMillies: 0,
    arrivalInMillies: 0,
    departureTimeDisplay: '',
    arrivalTimeDisplay: '',
    durationDisplay: '',
    durationInMillies: 0,
    departureAirportCode: '',
    arrivalAirportCode: '',
    stops: [],
    classTypes: [
      { code: 'BC', name: $localize`Basic`, price: 190, seatsLeft: null },
      { code: 'MN', name: $localize`Main`, price: 240, seatsLeft: null },
      { code: 'EC', name: $localize`Economy`, price: 475, seatsLeft: null },
    ],
  },
  {
    airlineName: $localize`Vistara Airways`,
    airlineId: `Vistara Airways`,
    airlineLogo: '',
    departureDate: new Date('01/12/2024 12:00'),
    arrivalDate: new Date('01/12/2024 15:00'),
    departureInMillies: 0,
    arrivalInMillies: 0,
    departureTimeDisplay: '',
    arrivalTimeDisplay: '',
    durationDisplay: '',
    durationInMillies: 0,
    departureAirportCode: '',
    arrivalAirportCode: '',
    stops: [],
    classTypes: [
      { code: 'BC', name: $localize`Basic`, price: 130, seatsLeft: null },
      { code: 'MN', name: $localize`Main`, price: 240, seatsLeft: null },
      { code: 'EC', name: $localize`Economy`, price: 475, seatsLeft: null },
    ],
  },
  {
    airlineName: $localize`Indigo Airline`,
    airlineId: `Indigo Airline`,
    airlineLogo: '',
    departureDate: new Date('01/12/2024 7:20'),
    arrivalDate: new Date('01/12/2024 10:50'),
    departureInMillies: 0,
    arrivalInMillies: 0,
    departureTimeDisplay: '',
    arrivalTimeDisplay: '',
    durationDisplay: '',
    durationInMillies: 0,
    departureAirportCode: '',
    arrivalAirportCode: '',
    stops: [],
    classTypes: [
      { code: 'BC', name: $localize`Basic`, price: 115, seatsLeft: null },
      { code: 'MN', name: $localize`Main`, price: 240, seatsLeft: null },
      { code: 'EC', name: $localize`Economy`, price: 475, seatsLeft: null },
    ],
  },
  {
    airlineName: $localize`Air India`,
    airlineId: `Air India`,
    airlineLogo: '',
    departureDate: new Date('01/12/2024 9:10'),
    arrivalDate: new Date('01/12/2024 13:30'),
    departureInMillies: 0,
    arrivalInMillies: 0,
    departureTimeDisplay: '',
    arrivalTimeDisplay: '',
    durationDisplay: '',
    durationInMillies: 0,
    departureAirportCode: '',
    arrivalAirportCode: '',
    stops: [],
    classTypes: [
      { code: 'BC', name: $localize`Basic`, price: 125, seatsLeft: null },
      { code: 'MN', name: $localize`Main`, price: 240, seatsLeft: null },
      { code: 'EC', name: $localize`Economy`, price: 475, seatsLeft: null },
    ],
  },
];
